const mywork = [
  {
    img: "assets/img/cases/wedding.jpg",
    imgD: "assets/img/cases/wedding-d.jpg",
    name: "My Wedding Page",
    tags: "婚禮邀請、留言板",
    cate: 5,
    link: "https://ally-chen.github.io/wedding/",
  },
  {
    img: "assets/img/cases/miniGame.jpg",
    imgD: "assets/img/cases/miniGame-d.jpg",
    name: "輔大合氣道招生活動",
    tags: "問答小測驗、Google Spreadsheet",
    cate: 5,
    link: "https://web.ntnu.edu.tw/~40105018E/FJUAikidoClub/",
  },
  {
    img: "assets/img/cases/playback.jpg",
    imgD: "assets/img/cases/playback-d.jpg",
    name: "Playback",
    tags: "影音平台",
    cate: 1,
    link: "https://web.ntnu.edu.tw/~40105018E/demo/playback",
  },
  {
    img: "assets/img/cases/kmtelection.jpg",
    imgD: "assets/img/cases/kmtelection-d.jpg",
    name: "2022 KMT選舉資訊站",
    tags: "形象官網",
    cate: 1,
    link: "https://web.ntnu.edu.tw/~40105018E/FJUAikidoClub/",
  },
  {
    img: "assets/img/cases/isloungeGuide.jpg",
    imgD: "assets/img/cases/isloungeGuide-d.jpg",
    name: "Is Lounge - 如何挑選",
    tags: "JQuery互動頁面",
    cate: 1,
    link: "https://www.is-lounge.com/guide",
  },
  {
    img: "assets/img/cases/wecharmingAntifraud.jpg",
    imgD: "assets/img/cases/wecharmingAntifraud-d.jpg",
    name: "唯睛品 - 反詐騙聲明",
    tags: "靜態資訊頁面",
    cate: 2,
    link: "https://www.wecharming.life/antifraud",
  },
  {
    img: "assets/img/cases/supportan.jpg",
    imgD: "assets/img/cases/supportan-d.jpg",
    name: "倍速",
    tags: "靜態資訊頁面",
    cate: 1,
    link: "https://www.fresenius-kabi-en.com.tw/supportan/",
  },
  {
    img: "assets/img/cases/gogoBus.jpg",
    imgD: "assets/img/cases/gogoBus-d.jpg",
    name: "GoGo Bus",
    tags: "前端修練精神時光屋作品、PTX API",
    cate: 4,
    link: "https://ally-chen.github.io/gogoBus",
  },
  {
    img: "assets/img/cases/twBike.jpg",
    imgD: "assets/img/cases/twBike-d.jpg",
    name: "台灣好行",
    tags: "前端修練精神時光屋作品、PTX API",
    cate: 4,
    link: "https://ally-chen.github.io/2021f2eChallenge/#/bike",
  },
  {
    img: "assets/img/cases/indianmc.jpg",
    imgD: "assets/img/cases/indianmc-d.jpg",
    name: "印地安美式重機",
    tags: "品牌重機、官網首頁更新",
    cate: 2,
    css: "Bootstrap + 客製切版",
    link: "https://www.indianmotorcycle.com.tw/",
  },
  {
    img: "assets/img/cases/decantus.jpg",
    imgD: "assets/img/cases/decantus-d.jpg",
    name: "岱卡提夫",
    tags: "線上購物",
    cate: 2,
    css: "Bootstrap + 客製切版",
    link: "https://www.decantusasia.com/",
  },
  {
    img: "assets/img/cases/smc.jpg",
    imgD: "assets/img/cases/smc-d.jpg",
    name: "南天書局",
    tags: "官網更新、靜態轉RWD設計",
    cate: 2,
    css: "Bootstrap",
    link: "https://www.smcbook.com.tw/smc/",
  },
  {
    img: "assets/img/cases/goodsaddict.jpg",
    imgD: "assets/img/cases/goodsaddict-d.jpg",
    name: "強石磁鐵",
    tags: "線上購物、文創商品",
    cate: 1,
    css: "RWD客製切版",
    link: "https://goodsaddict.com/",
  },
  {
    img: "assets/img/cases/dakini.jpg",
    imgD: "assets/img/cases/dakini-d.jpg",
    name: "DakiniDeesse",
    tags: "形象官網、保養品牌",
    cate: 2,
    css: "Bootstrap + 客製切版",
    link: "https://www.dakinideesse.com/",
  },
  {
    img: "assets/img/cases/innovative.jpg",
    imgD: "assets/img/cases/innovative-d.jpg",
    name: "英凡地毯",
    tags: "形象官網、地毯品牌代理",
    cate: 2,
    css: "Bootstrap + 客製切版",
    link: "https://www.innovativeworkplacetw.com/",
  },
  {
    img: "assets/img/cases/fusun.jpg",
    imgD: "assets/img/cases/fusun-d.jpg",
    name: "富山生活藥妝",
    tags: "線上購物、藥妝產品",
    cate: 2,
    css: "Bootstrap + 客製切版",
    link: "https://www.fusun168.com/",
  },
  {
    img: "assets/img/cases/lepenseur.jpg",
    imgD: "assets/img/cases/lepenseur-d.jpg",
    name: "奔騰思潮",
    tags: "部落格",
    cate: 2,
    css: "Bootstrap + 客製切版",
    link: "https://www.lepenseur.com.tw/",
  },
  {
    img: "assets/img/cases/kkbox.jpg",
    imgD: "assets/img/cases/kkbox-d.jpg",
    name: "KKBOX example",
    tags: "Vue、KKBOX openAPI",
    cate: 3,
    css: "RWD客製切版",
    link: "http://web.ntnu.edu.tw/~40105018E/kkbox/#/",
  },
  {
    img: "assets/img/cases/page.jpg",
    imgD: "assets/img/cases/page-d.jpg",
    name: "單頁切版練習",
    tags: "RWD",
    cate: 3,
    css: "",
    link: "https://tmumr.csb.app/",
  },
  {
    img: "assets/img/cases/todolist.jpg",
    imgD: "assets/img/cases/todolist-d.jpg",
    name: "Todo List(React)",
    tags: "React todo list example",
    cate: 3,
    css: "",
    link: "https://e6voq.csb.app/",
  },
  {
    img: "assets/img/cases/d3map.jpg",
    imgD: "assets/img/cases/d3map-d.jpg",
    name: "D3 Map example",
    tags: "D3.js",
    cate: 3,
    css: "",
    link: "https://web.ntnu.edu.tw/~40105018E/demo/d3-map/",
  },
  {
    img: "assets/img/cases/recycle.jpg",
    imgD: "assets/img/cases/recycle-d.jpg",
    name: "資源回收小測驗",
    tags: "Vue、interact.js",
    cate: 3,
    css: "簡易切版",
    link: "http://web.ntnu.edu.tw/~40105018E/demo/recycle/demo.html",
  },
  {
    img: "assets/img/cases/lunchoose2.jpg",
    imgD: "assets/img/cases/lunchoose2-d.jpg",
    name: "今天吃什麼 Lunchoose2.0",
    tags: "Random picker、Restful API(PHP)",
    cate: 5,
    link: "https://web.ntnu.edu.tw/~40105018E/lunchoose2.0",
  },
  {
    img: "assets/img/cases/lunchoose.png",
    imgD: "assets/img/cases/lunchoose-d.png",
    name: "今天吃什麼Lunchoose",
    tags: "Vue練習、適用選擇困難患者",
    cate: 3,
    css: "簡易切版",
    link: "http://web.ntnu.edu.tw/~40105018E/lunchoose/",
  },
]